### ISSUE TITLE
V1.1.0 Update to SU 2022 :)

### ISSUE THREAD

**Issue by nhafeng** [AntonSynytsia/MSPhysics#28]
*** To use MSPhysics in SU2022, you have to install SU2019 on your computer.  Otherwise, the plugin may not run in SU2022 ***
[ I don't know why .... ]

Please follow these steps:

1.
go to Extension Manager,
install ams_Lib_v3.6.0h.rbz (newest version 3.7.1)
install MSPhysics_v1.0.3.rbz
Exit SketchUp

2.
Get the files from 
https://github.com/AntonSynytsia/MSPhysics/tree/anton-ver110
unzip and copy all files & folders to replace the old versions:

C:\Users\user\AppData\Roaming\SketchUp\SketchUp 2022\SketchUp\Plugins

then you can find it works again!

=============
Thanks to AntonSynytsia, MSPhysics is amazing, I love it :)

**Comment by 2695429209** [comment]
其实并不需要额外安装2019版本的sketchup。因为早在之前我就发现是因为2020版本以及以上sketchup安装文件缺少了一个dl导致的错误，就是找个libogg-0.dll，
只需要把他移动到高版本2020以上就可以运行，再高的版本我没有测试，
但是我仍然发现会有bug的存在
当然我在就发现运行库的安装ams_Lib_v3.6.0h版本才好用，（最新版本3.7.1的配合会存在bug）
你的MSPhysics在高版本的右击的选项可以用吗
[动力学.zip](https://github.com/AntonSynytsia/MSPhysics/files/10193760/default.zip)

我的并不起作用
In fact, you do not need to install the 2019 version of sketchup. Because I found earlier that an error was caused by the lack of a dl in the sketchup installation files of 2020 and above, namely, finding a libogg-0.dll,
You just need to move it to a higher version than 2020 to run it. I have not tested the higher version,
But I still find that there are bugs
Of course, I found the runtime installation of AMS_ Lib_ The v3.6.0h version is easy to use. (There are bugs in the latest version 3.7.1.)
Can you use the right-click option of your MSPhysics in the higher version
Mine doesn't work

**Comment by nhafeng** [comment]
> 

谢谢，我试一下卸载SU2019，然后新装2022再加载这个测试下。

**Comment by nhafeng** [comment]
> 其实并不需要额外安装2019版本的sketchup。因为早在之前我就发现是因为2020版本以及以上sketchup安装文件缺少了一个dl导致的错误，就是找个libogg-0.dll， 只需要把他移动到高版本2020以上就可以运行，再高的版本我没有测试， 但是我仍然发现会有bug的存在 当然我在就发现运行库的安装ams_Lib_v3.6.0h版本才好用，（最新版本3.7.1的配合会存在bug） 你的MSPhysics在高版本的右击的选项可以用吗 [动力学.zip](https://github.com/AntonSynytsia/MSPhysics/files/10193760/default.zip)
> 
> 我的并不起作用 In fact, you do not need to install the 2019 version of sketchup. Because I found earlier that an error was caused by the lack of a dl in the sketchup installation files of 2020 and above, namely, finding a libogg-0.dll, You just need to move it to a higher version than 2020 to run it. I have not tested the higher version, But I still find that there are bugs Of course, I found the runtime installation of AMS_ Lib_ The v3.6.0h version is easy to use. (There are bugs in the latest version 3.7.1.) Can you use the right-click option of your MSPhysics in the higher version Mine doesn't work

确实，把您提供的 libogg-0.dll 复制到 SU 2022软件文件夹，启动SU的时候，MSPhysics不再报错了。
右击选项指什么？是右击在组件上现实的MSPhysics菜单吗？有显示。
另外，配合AMS_Lib 3.7.1b会有什么问题呢？我本着旧不如新，是非常想用最新版本的。

**Comment by nhafeng** [comment]
Here's steps to install MSPhysics for SU2022:

go to Extension Manager,
install ams_Lib_v3.6.0h.rbz (newest version 3.7.1)
install MSPhysics_v1.0.3.rbz

copy libogg-0.dll to SketchUp 2022's installation folder

Get the files from
https://github.com/AntonSynytsia/MSPhysics/tree/anton-ver110
unzip and copy all files & folders in (MSPhysics-anton-ver110/RubyExtension/*.*) to replace the old versions:

C:\Users\user\AppData\Roaming\SketchUp\SketchUp 2022\SketchUp\Plugins

Done.

**Comment by 2695429209** [comment]
frozen冻结无效

**Comment by 2695429209** [comment]
高版本可以上3.7.1，你自己试试看，反正我记得frozen这个效果设置好像是无效的

**Comment by nhafeng** [comment]
我用来放置一堆物件的，用到state=static，和frozen有什么区别没研究过。

**Comment by sriranjanr** [comment]
was anyone able to get set_slider_value function to work?

**Comment by bsikorsky** [comment]
> copy libogg-0.dll to SketchUp 2022's installation folder

copy libogg-0.dll to SketchUp 2022's installation folder

Where can this file be downloaded from?

**Comment by nhafeng** [comment]
> > copy libogg-0.dll to SketchUp 2022's installation folder
> 
> copy libogg-0.dll to SketchUp 2022's installation folder
> 
> Where can this file be downloaded from?

SU2019 has this file in its installed folder.

**Comment by bsikorsky** [comment]
> > > copy libogg-0.dll to SketchUp 2022's installation folder
> > 
> > 
> > copy libogg-0.dll to SketchUp 2022's installation folder
> > Where can this file be downloaded from?
> 
> SU2019 has this file in its installed folder.

I figured it out, thank you very much, it works

**Comment by smokhov** [comment]
(I've closed my #20 in favor of this)

**Comment by Sparksyyy** [comment]
C:\Users\61466\3D Objects\The Super Magnetic Motor 3.skp

**Comment by ronagoldberg** [comment]
Hi All,
I think I've followed all the directions but I'm getting this new error and I can't figure out how to fix it. I'd appreciate any help I can get.

Thanks,
Ron

Error Loading File C:/Users/Ron A Goldberg/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/MSPhysics/main_entry.rb
Error: #<NameError: undefined local variable or method `null' for main:Object>
C:/Users/Ron A Goldberg/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/MSPhysics/main_entry.rb:1:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2022/Tools/extensions.rb:197:in `require'
C:/Program Files/SketchUp/SketchUp 2022/Tools/extensions.rb:197:in `load'
C:/Users/Ron A Goldberg/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/MSPhysics.rb:23:in `register_extension'
C:/Users/Ron A Goldberg/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/MSPhysics.rb:23:in `<module:MSPhysics>'
C:/Users/Ron A Goldberg/AppData/Roaming/SketchUp/SketchUp 2022/SketchUp/Plugins/MSPhysics.rb:6:in `<top (required)>'

**Comment by SwissmountainVA** [comment]
I am not a programmer and have not used Github before and encountered very basic problems trying to implement the aforementioned instructions.

1. Where to download the ams_Lib_v3.6.0h.rbz file?
    On Sketchucation I can only see the current 3.7.1 file and in the Sketchup extension warehouse, they have Version 3.5.2.
    A Google search for ams_Lib_v3.6.0h.rbz returned no results.

2. How to get the updated "MS Physics" folder from Github. I can download each individual file in the folder, but there are     
    possibly a hundred files nested in separate folders. Somebody suggested to unzip the downloaded file. But how do I 
    download the folder as a zip file?

Any instruction is greatly appreciated, thank you

**Comment by SwissmountainVA** [comment]
I managed to answer one of my questions myself. Here is how to download a zip of the code:
<img width="701" alt="ZipFile" src="https://github.com/AntonSynytsia/MSPhysics/assets/142945157/83e14f2d-0f62-4275-8590-61da341ee383">


I still need help locating the ams_Lib_v3.6.0h.rbz file

**Comment by nhafeng** [comment]
GitHub - RBCGroup/ams_lib: A set of utilities for interacting with SketchUp window and geometry.

AMS Library releases are available at Extension Warehouse or SketchUcation Extension Store.



***@***.***
 
From: SwissmountainVA
Date: 2023-08-23 07:26
To: AntonSynytsia/MSPhysics
CC: Leo Zhang; Author
Subject: Re: [AntonSynytsia/MSPhysics] V1.1.0 Update to SU 2022 :) (Issue #28)
I managed to answer one of my questions myself. Here is how to download a zip of the code:
I still need help locating the ams_Lib_v3.6.0h.rbz file

**Comment by SwissmountainVA** [comment]
Thank you nhafeng, I can't find "ams_Lib_v3.6.0h.rbz" on either the extension warehouse or at Sketchucation, and installed the current version 3.7.1 from Sketchucation.

I tried following the steps without installing Sketchup Pro version 2019 and got an error message upon Sketchup 2022 startup.

I then installed SKPpro 2019 and simply copied  libogg-0.dll from that installation folder to the 2022 installation folder.

This worked and I now have the plugin showing up in my SKPpro2022.

I hope it works and am very excited to have MSphysics back if it does.

I would totally pay to have this plugin in an updated form.

Thank you to everyone contributing to make this plugin work again.

**Comment by TalhaMWattoo** [comment]
[MSPhysics v1.1 Beta](https://forums.sketchup.com/uploads/short-url/jWHb6DqrUaUXlPHpahLOKvkb2co.rbz)
Here is a repack which works with most cases and loads in SU 22 and 23. I just edited it to make it load. Other things are original code and might cause some errors at some points.
Had to edit and ams_lib check so if you previously installed it, uninstall before using this. It is packed within the rbz.

Disclaimer: All credit goes to the original authors for these amazing plugins, MSPhysics and ams_lib.

**Comment by ronagoldberg** [comment]
I tried to install the new file "MSPhysics v1.1 Beta.rbz" in SU 22 and 23 through the extension manager and it doesn't load. I don't get any errors. It's like nothing happened at all.

> [MSPhysics v1.1 Beta](https://forums.sketchup.com/uploads/short-url/jWHb6DqrUaUXlPHpahLOKvkb2co.rbz) Here is a repack which works with most cases and loads in SU 22 and 23. I just edited it to make it load. Other things are original code and might cause some errors at some points. Had to edit and ams_lib check so if you previously installed it, uninstall before using this. It is packed within the rbz.
> 
> Disclaimer: All credit goes to the original authors for these amazing plugins, MSPhysics and ams_lib.

**Comment by ronagoldberg** [comment]
The "MSPhysics v1.1 Beta" folder is in the plugins folder for both versions of SU but it doesn't appear as installed in the extension manager.


> [MSPhysics v1.1 Beta](https://forums.sketchup.com/uploads/short-url/jWHb6DqrUaUXlPHpahLOKvkb2co.rbz) Here is a repack which works with most cases and loads in SU 22 and 23. I just edited it to make it load. Other things are original code and might cause some errors at some points. Had to edit and ams_lib check so if you previously installed it, uninstall before using this. It is packed within the rbz.
> 
> Disclaimer: All credit goes to the original authors for these amazing plugins, MSPhysics and ams_lib.
![MSPhysics-Beta](https://github.com/AntonSynytsia/MSPhysics/assets/142690875/bff79283-13ae-4de8-867e-7341766e1506)

**Comment by ronagoldberg** [comment]
I figured it out.

Thanks for making this update!


> [MSPhysics v1.1 Beta](https://forums.sketchup.com/uploads/short-url/jWHb6DqrUaUXlPHpahLOKvkb2co.rbz) Here is a repack which works with most cases and loads in SU 22 and 23. I just edited it to make it load. Other things are original code and might cause some errors at some points. Had to edit and ams_lib check so if you previously installed it, uninstall before using this. It is packed within the rbz.
> 
> Disclaimer: All credit goes to the original authors for these amazing plugins, MSPhysics and ams_lib.

**Comment by cureter** [comment]
> I figured it out.
> 
> Thanks for making this update!
> 
> > [MSPhysics v1.1 Beta](https://forums.sketchup.com/uploads/short-url/jWHb6DqrUaUXlPHpahLOKvkb2co.rbz) Here is a repack which works with most cases and loads in SU 22 and 23. I just edited it to make it load. Other things are original code and might cause some errors at some points. Had to edit and ams_lib check so if you previously installed it, uninstall before using this. It is packed within the rbz.
> > Disclaimer: All credit goes to the original authors for these amazing plugins, MSPhysics and ams_lib.

Can you tell me how you managed it?
I copied the content from the rbz into my plugins folder. I could start MSPhysics but the pyhsics is not working all objects are stationary.

**Comment by TalhaMWattoo** [comment]
Just copy the contents within the folder to sketchup plugins directory. Not the actual folder. I messed it when zipping. Sorry for the confusion.

**Comment by TalhaMWattoo** [comment]
> > I figured it out.
> > Thanks for making this update!
> > > [MSPhysics v1.1 Beta](https://forums.sketchup.com/uploads/short-url/jWHb6DqrUaUXlPHpahLOKvkb2co.rbz) Here is a repack which works with most cases and loads in SU 22 and 23. I just edited it to make it load. Other things are original code and might cause some errors at some points. Had to edit and ams_lib check so if you previously installed it, uninstall before using this. It is packed within the rbz.
> > > Disclaimer: All credit goes to the original authors for these amazing plugins, MSPhysics and ams_lib.
> 
> Can you tell me how you managed it? I copied the content from the rbz into my plugins folder. I could start MSPhysics but the pyhsics is not working all objects are stationary.

Object states might be static. Check that if the toolbars load then it should work.
